apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
  namespace: secure-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: secure-app
      static_configs:
      - targets: ['ci-api-service.secure-app.svc.cluster.local:3000']
